execfile('1_import_pkgs.py')
execfile('2_epochs.py')
execfile('3_get_model_D7.py')
execfile('4_get_data.py')
execfile('5_divide_data.py')
execfile('6_fit_model.py')
execfile('7_learning_curve.py')
execfile('8_accuracy_7_3.py')
execfile('9_confusion_matrix_7_3.py')
#execfile('10_images_misclassified.py')
#execfile('11_mono_correct.py')
#execfile('12_poly_correct.py')

#print(model.layers)
#print(model.inputs)
#print(model.outputs)
