Bootstrap: docker
From: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

%help
To start your container simply try
singularity exec THIS_CONTAINER.simg bash

To use GPUs, try
singularity exec --nv THIS_CONTAINER.simg bash

Container based on recipe by drinkingkazu

%labels
Maintainer gnperdue
Version ubuntu16.04-py3-tf110-gpu

#------------
# Global installation
#------------
%environment
    export XDG_RUNTIME_DIR=/tmp/$USER
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}
    export CUDA_DEVICE_ORDER=PCI_BUS_ID

%post
    # add wilson cluster mount points
    mkdir /scratch /data /lfstev

    # apt-get
    apt-get -y update
    apt-get -y install dpkg-dev g++ gcc binutils libqt4-dev python3-dev python3-tk python3-pip openslide-tools git autoconf libtool build-essential 

    # pip
    python3 -m pip install --upgrade setuptools pip
    python3 -m pip install tensorflow-gpu==1.8.0
    python3 -m pip install h5py
    python3 -m pip install opencv-python
    python3 -m pip install numpy
    python3 -m pip install pandas
    python3 -m pip install notebook
    python3 -m pip install matplotlib
    python3 -m pip install jupyter
    python3 -m pip install ipython
    python3 -m pip install scikit-learn
    python3 -m pip install scikit-image
    python3 -m pip install scipy
    python3 -m pip install seaborn
    python3 -m pip install tqdm
    python3 -m pip install openslide-python
    python3 -m pip install Pillow
    python3 -m pip install Keras==2.2.0
    python3 -m pip install jedi
    python3 -m pip install pathlib
    
    
    
    python3 -m pip install seaborn
    python3 -m pip install tensorflow-gpu==1.9.0
    python3 -m pip install pathlib
    python3 -m pip install absl-py==0.2.2
    python3 -m pip install astor==0.6.2
    python3 -m pip install backcall==0.1.0
    python3 -m pip install bleach==1.5.0
    python3 -m pip install cloudpickle==0.5.3
    python3 -m pip install cycler==0.10.0
    python3 -m pip install Cython==0.28.3
    python3 -m pip install dask==0.17.5
    python3 -m pip install decorator==4.3.0
    python3 -m pip install entrypoints==0.2.3
    python3 -m pip install future==0.16.0
    python3 -m pip install gast==0.2.0
    python3 -m pip install grpcio==1.12.1
    python3 -m pip install h5py==2.8.0
    python3 -m pip install html5lib==0.9999999
    python3 -m pip install ipykernel==4.8.2
    python3 -m pip install h5py
    python3 -m pip install ipython==6.4.0
    python3 -m pip install ipython-genutils==0.2.0
    python3 -m pip install ipywidgets==7.2.1
    python3 -m pip install jedi==0.12.0
    python3 -m pip install Jinja2==2.10
    python3 -m pip install jsonschema==2.6.0
    python3 -m pip install jupyter==1.0.0
    python3 -m pip install jupyter-client==5.2.3
    python3 -m pip install jupyter-console==5.2.0
    python3 -m pip install jupyter-core==4.4.0
    python3 -m pip install Keras==2.0.0
    python3 -m pip install Keras-Applications==1.0.2
    python3 -m pip install Keras-Preprocessing==1.0.1
    python3 -m pip install kiwisolver==1.0.1
    python3 -m pip install lxml==4.2.2
    python3 -m pip install Markdown==2.6.11
    python3 -m pip install MarkupSafe==1.0
    python3 -m pip install matplotlib==2.2.2
    python3 -m pip install mistune==0.8.3
    python3 -m pip install nbconvert==5.3.1
    python3 -m pip install nbformat==4.4.0
    python3 -m pip install networkx==2.1
    python3 -m pip install notebook==5.5.0
    python3 -m pip install numexpr==2.6.6
    python3 -m pip install numpy==1.14.5
    python3 -m pip install opencv-python==3.4.1.15
    python3 -m pip install openslide-python==1.1.1
    python3 -m pip install pandas==0.23.1
    python3 -m pip install pandocfilters==1.4.2
    python3 -m pip install parso==0.2.1
    python3 -m pip install pexpect==4.6.0
    python3 -m pip install pickleshare==0.7.4
    python3 -m pip install Pillow==5.1.0
    python3 -m pip install prompt-toolkit==1.0.15
    python3 -m pip install protobuf==3.6.0
    python3 -m pip install ptyprocess==0.6.0
    python3 -m pip install Pygments==2.2.0
    python3 -m pip install pyparsing==2.2.0
    python3 -m pip install python-dateutil==2.7.3
    python3 -m pip install pytz==2018.4
    python3 -m pip install PyWavelets==0.5.2
    python3 -m pip install PyYAML==3.12
    python3 -m pip install pyzmq==17.0.0
    python3 -m pip install qtconsole==4.3.1
    python3 -m pip install scikit-image==0.14.0
    python3 -m pip install scikit-learn==0.19.1
    python3 -m pip install scipy==1.1.0
    python3 -m pip install Send2Trash==1.5.0
    python3 -m pip install simplegeneric==0.8.1
    python3 -m pip install six==1.11.0
    python3 -m pip install sklearn==0.0
    python3 -m pip install tables==3.4.4
    python3 -m pip install tensorboard==1.9.0
    python3 -m pip install termcolor==1.1.0
    python3 -m pip install terminado==0.8.1
    python3 -m pip install testpath==0.3.1
    python3 -m pip install tflearn==0.3.2
    python3 -m pip install Theano==1.0.2
    python3 -m pip install toolz==0.9.0
    python3 -m pip install tornado==5.0.2
    python3 -m pip install tqdm==4.23.4
    python3 -m pip install traitlets==4.3.2
    python3 -m pip install wcwidth==0.1.7
    python3 -m pip install Werkzeug==0.14.1
    python3 -m pip install widgetsnbextension==3.2.1
    python3 -m pip install wsisampler==0.0.2
